apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: db-wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: '123456'
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html
      volumes:
        - name: wordpress-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-wordpress
spec:
  selector:
    app: db-wordpress
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-wordpress
  template:
    metadata:
      labels:
        app: db-wordpress
    spec:
      containers:
        - name: db-wordpress
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: '123456'
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
          volumeMounts:
            - name: db-wordpress-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: db-wordpress-volume
          emptyDir: {}



