---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  labels:
    name: wordpress
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: wordpress
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    type: Container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-mysql
  namespace: wordpress
  labels:
    app: wordpress-config-map
data:
  MYSQL_DATABASE: wordpress
  MYSQL_RANDOM_ROOT_PASSWORD: "1"
  MYSQL_MAX_CONNECTIONS: "100"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: wordpress
type: Opaque
data:
  MYSQL_USER: d29yZHByZXNzCg==
  MYSQL_PASSWORD: MTIzNDU2Cg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-wordpress
  namespace: wordpress
  labels:
    app: wordpress-config-map
data:
  WORDPRESS_DB_HOST: db-wordpress
  WORDPRESS_DB_NAME: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_USER: d29yZHByZXNzCg==
  WORDPRESS_DB_PASSWORD: MTIzNDU2Cg==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data-wordpress
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  volumeName: wordpress-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: db-wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: '123456'
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html      
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-db-pv
  namespace: wordpress
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /db-wordpress
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-pvc
  namespace: wordpress
spec:
  volumeName: wordpress-db-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: db-wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: db-wordpress
  namespace: wordpress
spec:
  selector:
    app: db-wordpress
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-wordpress
  namespace: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: db-wordpress
  template:
    metadata:
      labels:
        app: db-wordpress
    spec:
      containers:
        - name: db-wordpress
          image: mysql:8.1.0
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vars-mysql
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vars-mysql
                  key: MYSQL_RANDOM_ROOT_PASSWORD
            - name: MYSQL_MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: vars-mysql
                  key: MYSQL_MAX_CONNECTIONS
          volumeMounts:
            - name: db-wordpress-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: db-wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-db-pvc
